import type { Metadata } from "next";
import "./globals.css";
import Header from "./component/Header";
import Footer from "./component/Footer";
// import { CartProvider } from '../lib/cartContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="__variable_5cfdac __variable_9a8899 antialiased" cz-shortcut-listen="true">
          <Header />
          {children}
          <Footer />
      </body>
    </html>
  );
}
